name: lanxi
description: SSH-First Server Management Tool
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartssh2: ^2.9.0
  dio: ^5.4.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  lints: ^3.0.0

flutter:
  uses-material-design: true
